services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build: ./app
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/flask_db
    depends_on:
      - db
      - redis

  nginx:
    image: bitnami/nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro
    depends_on:
      - backend

  nginx-vts-exporter:
    image: sophos/nginx-vts-exporter
    environment:
      - NGINX_STATUS=http://nginx:8080/status/format/json
    ports:
      - "9913:9913"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://user:pass@db:5432/flask_db?sslmode=disable"
    depends_on:
      - db

  node-exporter:
    image: prom/node-exporter:latest

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nginx-vts-exporter
      - postgres-exporter
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data: