global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'nginx-vts'
    static_configs:
      - targets: ['nginx-vts-exporter:9913']

  - job_name: 'flask'
    static_configs:
      - targets: ['backend:5000']